replicaCount: 2

image:
  repository: mbenadik/djangoapp
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000  # This will be ignored if Ingress is used

env: []

ingress:
  enabled: true
  className: localport
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts: []
  tls: []

resources: {}

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
