replicaCount: 2

image:
  repository: mbenadik/djangoapp
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000  # This will be ignored if Ingress is used

env:
  - name: FLASK_ENV
    value: test
  - name: FLASK_COLOR
    value: blue
  - name: DJANGO_PREFIX
    value: django

ingress:
  enabled: true
  className: localport
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: 192.168.56.108
      paths:
        - path: /django(.*)
          pathType: ImplementationSpecific
        - path: /djangostatic(.*)
          pathType: ImplementationSpecific
  tls: []

resources: {}

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
