apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-chart.fullname" . }}
  labels:
    {{- include "django-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort | default 30000 }}
      {{- end }}
  selector:
    {{- include "django-chart.selectorLabels" . | nindent 4 }}

